# https://www.maturin.rs/project_layout#adding-python-type-information
def tokenize(text: str, keep_whitespace: bool) -> list[str]: ...
def to_kana(text: str) -> str: ...
def number_to_words(number: int, form: str, *, noun: str | None) -> str: ...
def syllabicate(text: str) -> list[str]: ...
