# https://www.maturin.rs/project_layout#adding-python-type-information
def tokenize(text: str, *, keep_whitespace: bool | None = None) -> list[str]: ...
def to_kana(
    text: str,
    *,
    whitespace: Whitespace | None = None,
    ignore_pattern: str | None = None,
) -> str: ...
def number_to_words(number: int) -> str: ...
def syllabicate(text: str) -> list[str]: ...
