[package]
name = "ainu-utils-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "ainu_utils_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
ainu-utils = { path = "../ainu-utils" }
