name: "CI: Python"

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "ainu-utils-js/**"
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: x86_64
          args: --release --out dist --find-interpreter --manifest-path ./ainu-utils-python/Cargo.toml
          # sccache: 'true'
          manylinux: auto

      - name: pytest
        shell: bash
        run: |
          set -e
          pip install --upgrade "pip<20"
          pip install ainu-utils --find-links dist --force-reinstall
          pip install pytest
          cd ./ainu-utils-python && pytest