name: "Release: Rust"

env:
  CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

on:
  push:
    tags:
      - v*

defaults:
  run:
    working-directory: ainu-utils

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Publish package rust
        if: ${{ !contains(github.ref, 'rc') }}
        run: cargo publish --token ${CRATES_TOKEN}
