---
name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

env:
  TZ: "Asia/Tokyo"

# https://github.com/taiki-e/cargo-llvm-cov/tree/main?tab=readme-ov-file#continuous-integration
jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ainu-utils

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --codecov --output-path codecov.json

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: aynumosir/ainu-utils
